### ISSUE TITLE
b_frames_present in caqse of t1

### ISSUE THREAD

**Issue by Lis-TV** [nicholas-fr/test-content-validation#10] opened 2022-12-28 17:17 UTC
In case of t1 we have:

 _"b_frames_present": {
            "expected": true,
            "detected": false,
            "test_result": "fail"
        },_

The t1 does not have any requirement related to b frames.

**Comment by nicholas-fr** [comment] 2023-04-06 09:59
Duplicate of https://github.com/nicholas-fr/test-content-validation/issues/13, b-frame presence now only checked if specified explicitly by the sparse matrix.

**Closed as completed by nicholas-fr** 2023-04-06 09:59 UTC
